trigger:
  branches:
    include:
    - master
    - no-docker
  tags:
    include:
    - "*"

stages:
  - stage: CI
    condition: not(or(startsWith(variables['Build.SourceBranch'], 'refs/tags'), contains(variables['Build.SourceBranchName'], 'release-')))
    jobs:
    - job: Build
      strategy:
        matrix:
          linux:
            imageName: 'ubuntu-20.04'
            CXX: g++
          linux_superbuild:
            imageName: 'ubuntu-20.04'
            CXX: g++
            SUPERBUILD: 'ON'
            TILEDB_FORCE_ALL_DEPS: 'OFF'
          macOS:
            imageName: 'macOS-12'
            CXX: clang++

      pool:
        vmImage: $(imageName)
      steps:
      - template: scripts/azure-linux_mac.yml

