name: nightly
on:
  push:
    paths:
      - '.github/workflows/nightly.yaml'
      - 'scripts/nightly/**'
  schedule:
    - cron: "0 2 * * *" # Every night at 2 AM UTC (9 PM EST; 10 PM EDT)
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: nightly-${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-12", "ubuntu-20.04"]
    env:
      TILEDB_FORCE_ALL_DEPS: OFF
    steps:
      - name: Clone libtiledb
        uses: actions/checkout@v3
        with:
          repository: TileDB-Inc/TileDB
          ref: dev
          path: libtiledb
      - name: Clone MariaDB
        uses: actions/checkout@v3
        with:
          repository: MariaDB/server
          ref: mariadb-10.5.13
          path: mariadb
      - name: Clone TileDB-Inc/TileDB-MariaDB
        uses: actions/checkout@v3
        with:
          path: mariadb/storage/mytile
      - name: Setup Ubuntu
        if: runner.os == 'Linux'
        run: sudo bash mariadb/storage/mytile/scripts/nightly/setup-ubuntu.sh
      - name: Setup macOS
        if: runner.os == 'macOS'
        run: bash mariadb/storage/mytile/scripts/nightly/setup-macos.sh
      - name: Build libtiledb
        run: bash mariadb/storage/mytile/scripts/nightly/build-libtiledb.sh
      - name: Build TileDB-MariaDB
        run: bash mariadb/storage/mytile/scripts/nightly/build-tiledb-mariadb.sh
