name: nightly

on:
  push:
    paths:
      - '.github/workflows/nightly.yaml'
      - 'scripts/ci/**'
  pull_request:
    paths:
      - '.github/workflows/nightly.yaml'
      - 'scripts/ci/**'
  schedule:
    - cron: "0 2 * * 0" # Every Sunday night at 2 AM UTC (9 PM EST; 10 PM EDT)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    name: nightly
    env:
      OWNER_TILEDB_MARIADB: ${{ github.repository_owner }} # support building from a fork
      REF_MARIADB: mariadb-11.0.2
      REF_LIBTILEDB: main
      REF_TILEDB_MARIADB: ${{ github.sha }}
      TILEDB_FORCE_ALL_DEPS: OFF
    steps:
      # This initial checkout is only to obtain the CI scripts
      - uses: actions/checkout@v4
      - name: Clone and checkout repos
        run: bash scripts/ci/checkout.sh
      - name: Setup
        run: sudo bash scripts/ci/setup-ubuntu.sh
      - name: Build libtiledb
        run: bash scripts/ci/build-libtiledb.sh
      - name: Build TileDB-MariaDB
        run: bash scripts/ci/build-tiledb-mariadb.sh
  issue:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    needs: build
    if: ( failure() || cancelled() ) && github.repository_owner == 'TileDB-Inc' && github.event_name == 'schedule'
    steps:
      - uses: actions/checkout@v4
      - name: Open Issue
        uses: TileDB-Inc/github-actions/open-issue@main
        with:
          name: nightly build
          label: nightly-failure
          assignee: DimitrisStaratzis,ihnorton,Shelnutt2
        env:
          TZ: "America/New_York"
