name: stable

# This workflow should run on every tag, master branch and pull requests. Also, can be triggered manually.
on:
  workflow_dispatch:
  push:
    tags:
      - '*'
    branches:
      - 'master'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    name: stable-${{ matrix.superbuild && 'superbuild' || 'default' }}
    strategy:
      fail-fast: false
      matrix:
        superbuild: [true, false]
    env:
      OWNER_TILEDB_MARIADB: ${{ github.repository_owner }} # support building from a fork
      REF_MARIADB: mariadb-11.0.2
      REF_LIBTILEDB: 2.28.0
      REF_TILEDB_MARIADB: ${{ github.sha }}
      TILEDB_FORCE_ALL_DEPS: OFF
    steps:
      # This initial checkout is only to obtain the CI scripts
      - uses: actions/checkout@v4
      - name: Clone and checkout repos
        run: bash scripts/ci/checkout.sh
      - name: Setup
        run: sudo bash scripts/ci/setup-ubuntu.sh
      - name: Build libtiledb
        if: ${{ ! matrix.superbuild }}
        run: bash scripts/ci/build-libtiledb.sh
      - name: Build TileDB-MariaDB
        run: bash scripts/ci/build-tiledb-mariadb.sh
  deploy:
    needs: build
    if: github.repository_owner == 'TileDB-Inc' && (startsWith(github.ref, 'refs/tags/') || github.ref_name == github.event.repository.default_branch)
    uses: ./.github/workflows/docker.yaml
    secrets: inherit
